name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run CI tests
        run: |
          # Replace this command with your CI test commands
          echo "Running CI tests..."
          python
  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t subhaganesh/mark-app:mydemo .

      - name: Push Docker image to Docker Hub
        run: docker push subhaganesh/mark-app:mydemo

  deploy:
    needs: cd
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          # Replace the following commands with your deployment steps
          echo "Deploying the Docker image to production..."
          # Example commands:
          # - ssh to production server
          # - pull the latest Docker image
          # - stop and remove the existing container
          # - start a new container with the updated image





