name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t subhaganesh/mark-app:mydemo .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull Docker image
        run: docker pull subhaganesh/mark-app:mydemo

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 subhaganesh/mark-app:mydemo
          sleep 10s # Wait for the container to start

      - name: Get container IP address
        run: |
          CONTAINER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q))
          echo "Container IP: $CONTAINER_IP"
          echo "::set-output name=container_ip::$CONTAINER_IP"



